/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as InsideRouteImport } from './routes/inside'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WhyTypeBRouteImport } from './routes/why-type-b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const InsideRoute = InsideRouteImport.update({
  id: '/inside',
  path: '/inside',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyTypeBRoute = WhyTypeBRouteImport.update({
  id: '/why-type-b',
  path: '/why-type-b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/inside': typeof InsideRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/why-type-b': typeof WhyTypeBRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/inside': typeof InsideRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/why-type-b': typeof WhyTypeBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/inside': typeof InsideRoute
  '/reviews': typeof ReviewsRoute
  '/shop': typeof ShopRoute
  '/why-type-b': typeof WhyTypeBRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/faq'
    | '/features'
    | '/inside'
    | '/reviews'
    | '/shop'
    | '/why-type-b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/faq'
    | '/features'
    | '/inside'
    | '/reviews'
    | '/shop'
    | '/why-type-b'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendar'
    | '/faq'
    | '/features'
    | '/inside'
    | '/reviews'
    | '/shop'
    | '/why-type-b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  InsideRoute: typeof InsideRoute
  ReviewsRoute: typeof ReviewsRoute
  ShopRoute: typeof ShopRoute
  WhyTypeBRoute: typeof WhyTypeBRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inside': {
      id: '/inside'
      path: '/inside'
      fullPath: '/inside'
      preLoaderRoute: typeof InsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-type-b': {
      id: '/why-type-b'
      path: '/why-type-b'
      fullPath: '/why-type-b'
      preLoaderRoute: typeof WhyTypeBRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  InsideRoute: InsideRoute,
  ReviewsRoute: ReviewsRoute,
  ShopRoute: ShopRoute,
  WhyTypeBRoute: WhyTypeBRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
